mccode-dev/mccode-antlr

mccode_antlr/io/hdf5.py, test/test_io.py
Storing any `mccode_antlr` object into an HDF5 file requires keeping track of the non-default properties of the object _plus_ minimal metadata about the object and the version of `mccode_antlr`.
At the moment the version is required to be equal at writing and reading time, to protect against internal object changes during this pre-`v1.0` era.
Eventually there could be a softening of this requirement, potentially with some built-in equivalency graph and/or automatic conversion.
The object metadata is only its name at present, e.g., `mccode_antlr.instr.Instr` must store `'Instr'` as an attribute of the HDF5 group that it is written into.
The first approach to record this metadata was to store both the module and object metadata as separate attributes for every group. This seemed wasteful, …
=> Refactor HDF5 module and object information

mccode_antlr/instr/visitor.py, mccode_antlr/io/hdf5.py, test/test_io.py
=> Fix component instance `METADATA` declaration parsing

.github/workflows/pip.yml, mccode_antlr/compiler/c.py, mccode_antlr/config/platforms.yaml, test/test_instr.py, test/test_io.py
Most tests in the `pytest` test suite are pure-Python and can be run on all runners. There are, at present, two compiled `Instr` tests which likely will not work on a Windows runner -- one of which uses `mcpl` which must be installed to work.
The compiled tests are moved to new `TestCase` classes which skip their contained test cases if the operating system is Windows. And the MCPL based test additionally checks for the successful evaluation of `mcpl-tool --version` via a `subprocess` run invocation.
=> Re-enable `pytest` based tests for GitHub Actions Workers

mccode_antlr/translators/c_decls.py, test/test_instr.py
[Add] quotes around metadata string in C, [Extend] compiled instr test to include metadata.
Fixes #10
=> Fix missing-metadata-quotes issue

mccode_antlr/common/expression.py, mccode_antlr/instr/instance.py, mccode_antlr/instr/instr.py, mccode_antlr/translators/target.py, test/test_instr.py
Instrument parameter names can be used for setting component parameter values, including as part of valid `C` expressions. This is achieved by replacing a component instance parameter value from it's 'bare' identifier, e.g., `x`, to the value contained in the global instrument variable, `instrument_var.parameters.x`, which requires keeping track that the bare identifier _represents_ an instrument parameter.
This book keeping is handled by setting a flag on the `Value` holding the identifier.
When parsing a complete instrument file, the flag can be (and is) set correctly since there is a requirement that all instrument parameters are defined at the top of the file.
When 'assembling' an instrument the same is not necessarily true, and fixing this oversight requires one of two changes:
1. …
=> [Add] pre-translation check if identifiers are instrument parameter names

mccode_antlr/translators/c_decls.py, mccode_antlr/translators/c_finally.py, mccode_antlr/translators/c_initialise.py, test/test_instr.py
`vector` valued component parameters are (again) represented by pointers in their component-type parameter struct.
If initialised by an initialiser list in the instance definition, an equal-size memory allocation is made in the _instance_ initialization function, and the individual entries are then set -- one per line.
If the instance definition uses a pointer to initialise the value, no memory is allocated in the `_setpos` function.
The memory allocated by the instance initialiser is freed during the `FINALLY` step, so no  memory is leaked as a result of this change.
=> [Fix] vector initializer bug #20

mccode_antlr/common/metadata.py, mccode_antlr/comp/visitor.py, mccode_antlr/instr/visitor.py, test/test_metadata.py
Fixes #22 plus a few other issues found in `MetaData` parsing
- The `Comp` visitor did not strip double quotes from `StringLiteral` `mimetype` and `name` values, but the `Instr/Instance` visitor did. Now all variants strip the surrounding quotes (if a name has spaces, the quotes get added back for C output purposes).
- The `Instance` visitor incorrectly identified the source of any `MetaData` as coming from a component definition file
- The `Instance` visitor _also_ incorrectly identified the source name of any `MetaData` as the _name of the metadata_.
=> [Fix] metadata issues [Add] better metadata tests

mccode_antlr/instr/instance.py, mccode_antlr/translators/c_initialise.py, test/test_component_vector_parameter.py
Fixes #24 
Assembled and parsed `DECLARE`d arrays used as instance parameters are now handled equivalently.
=> [Fix] Assembled component instance with component vector parameter

mccode_antlr/translators/c_header.py
Resolves #26 by adding the `mccode-antlr` module version as a comment to the header of generated C files.
=> [Add] mccode-antlr version to generated C file header

mccode_antlr/instr/instr.py, mccode_antlr/instr/orientation.py, test/test_instr.py
Fixes #32 by converting dangling component references in `Instance.at_relative` and `Instance.rotate_relative` to the equivalent `'ABSOLUTE'` positions/angles via the `Instance.orientation` object.
This _should_ be sufficient, but perhaps a more-extensive test is in order.
=> [Fix] dangling component instance references post-split

mccode_antlr/instr/instr.py, test/test_instr.py
By keeping the split component in both returned `Instr` object, we maintain a reference to its location in both instruments.
This can allow better relational positioning of components in the second instrument.
=> [Refactor] Instr.split to keep split-component in both Instrs

mccode_antlr/instr/instr.py, test/test_instr.py
Now with extended tests to _ensure_ that components later in a split-instrument are still positioned relatively.
The dangling-reference check was too-restrictive in checking that `second.components` contained the referenced component `Instance`. The check has been modified to ensure
1. the component instance _name_ is present in the second instrument
2. if it is, that the reference to the second-instrument named component is used
=> [Fix] dangling component reference check in Instr.split

mccode_antlr/reader/registry.py, mccode_antlr/translators/target.py
- Add a `version` property to the `Registry` and `LocalRegistry` classes to avoid accessing an undefined object property.
- Update the `TargetVisitor`'s `configure_file` method to pull-out information for _the correct_ registry -- that is the one that provided the to-be-configured file.
=> [Fix] Issue #51

mccode_antlr/run/__init__.py, mccode_antlr/run/range.py, mccode_antlr/run/runner.py, pyproject.toml, tests/runtime/compiled.py
- The test utility `compile_and_run` is refactored to make use of the new commands.
- Existing tests pass, but no new tests are added yet to cover, e.g., the scan functionality.
- Entrypoint scripts are added for `mcrun-antlr` and `mxrun-antlr` to emulated `mcrun` and `mxrun`, respectively
=> [Add] run submodule with usable compile, run, and scan commands

mccode_antlr/config/config_default.yaml, mccode_antlr/reader/registry.py, pyproject.toml, tests/test_registry.py
Fixes #57 by adding a configuration variable for 'mccode-pooch' tag version
By default, the variable is 'latest' to select the most-recent tag (determined when loading the mccode_antlr module).
A user _should_ be able to override this by setting a different value in the module's config file (location platform dependent).
An error is thrown if no tag matches the specified value.
Only the default 'latest' has been tested thus far.
=> Use latest mccode-pooch tag instead of 'main'

mccode_antlr/run/runner.py, pyproject.toml
Move the command line entrypoint function names and re-use  `mccode_run`, `mcstas_run` and `mcxtrace_run` for in-Python scripting.
This will allow for, e.g., `mcstas_run(instr_obj, runtime_directory)` if only the 'default' McStas Registry and Generator are needed.
=> [Ref] expose run in Python for Instr objects

mccode_antlr/instr/instr.py
Keyword arguments `output_component` and `input_component` are added with default `None` values.
If not provided (or provided as `None`), they are replaced by their previous de facto values `'MCPL_output'` and `'MCPL_input'`, respectively.
=> [Add] output_component and input_component keywords to Instr.mcpl_split

mccode_antlr/loader/simfile.py
=> [Fix] broken sim file reader for 0-D detectors

src/mccode_antlr/assembler/assembler.py, src/mccode_antlr/common/expression.py, src/mccode_antlr/comp/comp.py, src/mccode_antlr/instr/instance.py, src/mccode_antlr/instr/instr.py, src/mccode_antlr/instr/orientation.py, src/mccode_antlr/loader/loader.py, src/mccode_antlr/translators/c.py, src/mccode_antlr/translators/c_decls.py, src/mccode_antlr/translators/c_defines.py, src/mccode_antlr/translators/c_header.py, src/mccode_antlr/translators/c_initialise.py, src/mccode_antlr/translators/c_listener.py, src/mccode_antlr/translators/c_trace.py, tests/instr/test_instance_parameters.py, tests/runtime/test_examples.py, tests/test_c_type_declaration.py, tests/test_extract.py
Mostly fixes #74 by handling more valid declaration (+initialization) statements.
Still missing is _any_ component `struct` member `struct` initialization -- but this isn't used in existing example instruments, so maybe isn't necessary.
=> Improved declared-variable parsing

src/mccode_antlr/assembler/assembler.py, src/mccode_antlr/reader/reader.py, src/mccode_antlr/reader/registry.py, src/mccode_antlr/translators/c.py, src/mccode_antlr/translators/target.py
By default, McCode repository registries are priority `-10`, 
'normal' registries are `0`, 
'local' (folder based) registries are `10`,
and in-memory registries are `100`.
This should ensure that user-provided files are used before any 'official' remote files.
If this works, then it fixes #73
=> Add a priority number to each registry and sort to start each search with the highest priority

src/mccode_antlr/config/platforms.yaml, src/mccode_antlr/instr/instr.py
- Adds support for the GNU Scientific Library flags and 'XRL' flags configured by McStas and/or McXtrace.
- Adds support for _any_ such flag specified as `@{LIBRARY}FLAGS@` which is replaced by `-llibrary` if not found in the system config file.
=> [Add] support for @LIBRARYFLAGS@ replacements

src/mccode_antlr/reader/registry.py
The `Reader` asks each `Registry` in turn if it 'knows' a filename. If it does, that `Registry` is then used to retrieve the file 'fullname', 'path', or contents. In the case of `LocalRegistry` the component is searched for in a more-restrictive way for the three latter cases, allowing for the possibility that a `LocalRegistry` 'knows' it has a file but can't find it.
This makes the later checks less stringent, fixing #79, which _could_ have the effect of allowing multiple matches for a file, especially if two copies of the same file (with modifications, presumably) exist in the same directory tree.
For now, this possible drawback is not blocking, since if there is a directory structure like
```
/
├ backup
│   └ ComponentA
│       └ ComponentA.instr
└ ComponentA
   └ ComponentA.instr
``` …
=> [Fix] LocalRegistry known/fullname glob inconsistency

src/mccode_antlr/translators/c_initialise.py, tests/runtime/test_examples.py
This pull request includes changes to both the `src/mccode_antlr/translators/c_initialise.py` file and the `tests/runtime/test_examples.py` file. The changes improve the handling of parameter assignments in the initialization code and add a new test for struct instance parameters.
Improvements to parameter handling:
* [`src/mccode_antlr/translators/c_initialise.py`](diffhunk://#diff-811164eb2dae1d151d29d0aa5adcab9f2137ab2590018b9c9ad05a91f99ce5a1L116-R119): Enhanced the `parameter_line` function to handle operations (e.g., function calls, struct member access). This change ensures that identifiers, string literals, and operations are correctly managed.
New test addition:
* [`tests/runtime/test_examples.py`](diffhunk://#diff-b96c745c98ec0b3f59eb2e6d3742d6eb58d044d02b604b1a1d6b0fa0a69fa0acR1 …
=> Component instance string-valued parameter setting error

src/mccode_antlr/translators/c_listener.py, tests/test_c_type_declaration.py
This pull request focuses on enhancing the handling of multi-dimensional arrays in the `src/mccode_antlr/translators/c_listener.py` file. The changes include updating the `CDeclarator` class to support tuples for array dimensions, introducing a new utility function to extract initializer sizes, and modifying test cases accordingly.
Key changes include:
* [`src/mccode_antlr/translators/c_listener.py`](diffhunk://#diff-3082e2ca4789ba1d4acbc2a36865b786b1e5bc67c7c42a3b3d488b9378cc17dfL104-R111): Updated the `CDeclarator` class to use tuples for the `elements` attribute, ensuring better support for multi-dimensional arrays. Added a `__post_init__` method to convert `elements` to a tuple if necessary.
* [`src/mccode_antlr/translators/c_listener.py`](diffhunk://#diff-3082e2ca4789ba1d4acbc2a36865b …
=> Issue 87 static arrays of arrays

src/mccode_antlr/assembler/assembler.py, src/mccode_antlr/reader/reader.py, src/mccode_antlr/reader/registry.py
Fixes #92 by requiring that the named component file matches the requested name, and raising an error if the loaded file defines a component with a different name.
=> [Fix] remote registry component resolution

src/mccode_antlr/translators/c.py, src/mccode_antlr/translators/c_initialise.py, src/mccode_antlr/translators/c_trace.py
- Initialization-time output of the code generator to setup NeXus groups for each component was missing, and has now been added.
- There was an pre-processor macro based on `MULTICORE` which McCode removed at some point, and is now removed here too.
- A new libc verison check is an indication of the last-synchronization point for McCode code generator changes.
=> Synchronize changes from McCode code generator

src/mccode_antlr/config/platforms.yaml, src/mccode_antlr/instr/instance.py, src/mccode_antlr/instr/instr.py, src/mccode_antlr/translators/c.py, src/mccode_antlr/translators/c_header.py, src/mccode_antlr/translators/c_raytrace.py, src/mccode_antlr/translators/target.py, tests/runtime/test_raytrace.py
https://github.com/McStasMcXtrace/mccode-antlr/issues/109
@g5t I've tested this functional at least for `ISIS_CRISP.instr`, built a patched `mccode-antlr` and generated attached c-code locally on my Mac, transported to my 8-way GPU machine and ran on all the GPUS in parallel there:
[ISIS_CRISP.c.txt](https://github.com/user-attachments/files/18694708/ISIS_CRISP.c.txt)
For a reason I do not yet fully understand the code generated for NCrystal_example (perhaps 2 instances of the NCrystal_sample?) still fails to compile w/OpenACC.
[NCrystal_example.c.txt](https://github.com/user-attachments/files/18694733/NCrystal_example.c.txt)
=> INCOMPLETE Corrections for NOACC component type when targeting GPU / OpenACC

src/mccode_antlr/compiler/c.py, src/mccode_antlr/loader/loader.py, tests/runtime/test_nexus.py
As found by @willend `instr` level `DEPENDENCY` specifications were indeed being omitted, due to a typo when combining component and instrument flags (`=` in place of `+=`).
The `@NEXUSFLAGS@` keyword in `CFLAGS` is being converted to the system-specific set of compiler flags -- I can't verify if these 
are actually correct or not however.
This should fix #112 
---
A test is added for the instrument dependency (including that not-setting the macro should work as expected, unlike `USE_OFF` which is automatically unset/set by the presence of OpenACC macros).
Similarly a test checks that the `@NEXUSFLAGS@` keyword gets expanded; a better test would actually check if that results in anything changing in the runtime.
=> Correct `DEPENDENCY` concatenation

src/mccode_antlr/reader/registry.py, src/mccode_antlr/translators/c_header.py, src/mccode_antlr/translators/c_particle.py, tests/runtime/compiled.py, tests/runtime/test_mcxtrace.py
As indicated by @willend in #113 the translation performed by, e.g., `mcxtrace-antlr`, does not produce a file which can compile.
This is due to different `_class_particle` struct definitions between `McStas` and `McXtrace` and simply overlooking this difference previously.
The different struct members are correctly handled by this PR, and a _very_ simple McXtrace test is added to ensure that a generated file can compile.
This fixes #113 barring other unrelated problems.
=> Implement C header specialization for McXtrace vs McStas

src/mccode_antlr/translators/c_header.py
Successfully locally tested, including manual steps of:
* local pip install
* local removal of lines `235-236` in `mccode_antlr/translators/c.py`
* added `mccode-r.h.in` int `$MCSTAS/share`
* ran with `mcstas-antlr -t -I${MCSTAS}` in `mctest --instr=BNL`
output available in https://new-nightly.mcstas.org/todays-datafiles/2025-04-25_output.html column 3
=> Fixes for #127 - sync with McCode main cogen.c.in

nightly/mccode_test.py, src/mccode_antlr/__init__.py, src/mccode_antlr/cli/commands.py, src/mccode_antlr/compiler/c.py, src/mccode_antlr/compiler/check.py, src/mccode_antlr/reader/registry.py, src/mccode_antlr/run/runner.py, src/mccode_antlr/translators/c.py, src/mccode_antlr/translators/c_header.py, src/mccode_antlr/translators/c_particle.py, src/mccode_antlr/translators/c_trace.py, src/mccode_antlr/translators/target.py, tests/instr/utils.py, tests/runtime/compiled.py, tests/runtime/test_instr.py, tests/runtime/test_raytrace.py, tests/runtime/test_when.py, tests/test_component_vector_parameter.py, tests/test_local_registry_collection.py
Fixes #139 by removing `Flavor` ternary operators in favor of the dictionary method described there.
All changes were made in the following commit:
- The `TargetVisitor` translator needs information about what specialization of McCode is being generated. This special information was held in a 'generator' dictionary with module-global defaults set for McStas and McXtrace (`MCSTAS_GENERATOR`, `MCXTRACE_GENERATOR`, respectively)/
- All information needed by the generator dictionary except the specialization URL could already be obtained from `Flavor` (with the 'project' id made easier to obtain by promoting `Flavor `to an `IntEnum`). So adding a `url()` method to `Flavor` allows dropping the module-global dictionaries.
- Making this change, a number of string-as-`Flavor` errors were …
=> More robust use of the `Flavor` enumerated value

pyproject.toml, src/mccode_antlr/__init__.py, src/mccode_antlr/cli/commands.py, src/mccode_antlr/cli/management.py, src/mccode_antlr/config/fallback.py, src/mccode_antlr/instr/instr.py, src/mccode_antlr/reader/__init__.py, src/mccode_antlr/reader/registry.py, src/mccode_antlr/translators/c.py, tests/test_registry.py
Since fully-fledged `MCPL` and `NCrystal` can be installed from PyPI, it's not difficult to imagine a user might want to use them with `mccode-antlr` with minimal hand-editing of the ``/.config/mccodeantlr/config.yml` file.
This adds a probably-most-often-used 'fallback' method to resolve `@{PROJECT}FLAGS@` McStas/McXtrace `DEPENDENCY` lines via `{project}-config --show buildflags` which both `MCPL` and `NCrystal` support, and are also the only two uses of the double @ escaped configuration keys.
Other minor functionality changes delay creating the `~/.cache/mccodeantlr` and `~/.config/mccodeantlr` folders, by removing the module-global `MCSTAS_REGISTRY`, `MCXTRACE_REGISTRY`, and `LIBC_REGISTRY` and instead accessing them only via `default_registries(flavor: Flavor)`. This required …
=> Compilation flag fallback

src/mccode_antlr/config/fallback.py
- As pointed out by @tkittel  `shutil.which` can be used instead of a subprocess call to which/where, and `subprocess.getstatusoutput` has been marked as a `legacy shell invocation`.
- Now `shutil.which` and `subprocess.run` are used, with any non-zero return code or any output to STDERR treated as a failure
=> [Fix] fallback subprocess calls
